USE [master]
GO
/****** Object:  Database [kawabunga]    Script Date: 12/18/2022 7:15:48 PM ******/
CREATE DATABASE [kawabunga]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kawabunga', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\kawabunga.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'kawabunga_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\kawabunga_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [kawabunga] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kawabunga].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [kawabunga] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [kawabunga] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [kawabunga] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [kawabunga] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [kawabunga] SET ARITHABORT OFF 
GO
ALTER DATABASE [kawabunga] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [kawabunga] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [kawabunga] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [kawabunga] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [kawabunga] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [kawabunga] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [kawabunga] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [kawabunga] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [kawabunga] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [kawabunga] SET  DISABLE_BROKER 
GO
ALTER DATABASE [kawabunga] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [kawabunga] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [kawabunga] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [kawabunga] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [kawabunga] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [kawabunga] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [kawabunga] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [kawabunga] SET RECOVERY FULL 
GO
ALTER DATABASE [kawabunga] SET  MULTI_USER 
GO
ALTER DATABASE [kawabunga] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [kawabunga] SET DB_CHAINING OFF 
GO
ALTER DATABASE [kawabunga] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [kawabunga] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [kawabunga] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [kawabunga] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'kawabunga', N'ON'
GO
ALTER DATABASE [kawabunga] SET QUERY_STORE = OFF
GO
USE [kawabunga]
GO
/****** Object:  Table [dbo].[data]    Script Date: 12/18/2022 7:15:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[data](
	[dataID] [int] IDENTITY(0,1) NOT NULL,
	[data] [varbinary](max) NOT NULL,
	[owner] [int] NOT NULL,
 CONSTRAINT [PK_data] PRIMARY KEY CLUSTERED 
(
	[dataID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 12/18/2022 7:15:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[userID] [int] IDENTITY(0,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password] [char](60) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_users] UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[data]  WITH CHECK ADD  CONSTRAINT [FK_data_users] FOREIGN KEY([owner])
REFERENCES [dbo].[users] ([userID])
GO
ALTER TABLE [dbo].[data] CHECK CONSTRAINT [FK_data_users]
GO
USE [master]
GO
ALTER DATABASE [kawabunga] SET  READ_WRITE 
GO
